name       : purple-facebook
version    : 0.9.4
release    : 3
source     :
    - https://github.com/dequis/purple-facebook/releases/download/v0.9.4-c9b74a765767/purple-facebook-0.9.4-c9b74a765767.tar.gz : cde5ef255668380abccf74b76844f95adf33e06421775ae302b93afbcb4eae8e
license    : GPL-2.0
component  : network.im
summary    : Pidgin Facebook Plugin
description: |
    Purple Facebook implements the Facebook Messenger protocol into pidgin, finch, and libpurple. While the primary implementation is for purple3, this plugin is back-ported for purple2.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(purple)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
