name       : purple-facebook
version    : 0.9.6
release    : 12
source     :
    - https://github.com/dequis/purple-facebook/releases/download/v0.9.6/purple-facebook-0.9.6.tar.gz : 1db6ed9e8f81cbd4ae10d75c04f5393e5cd4ca11ced74408ca6d07c7b888f3f7
license    : GPL-2.0-or-later
component  : network.im
summary    : Pidgin Facebook Plugin
description: |
    Purple Facebook implements the Facebook Messenger protocol into pidgin, finch, and libpurple. While the primary implementation is for purple3, this plugin is back-ported for purple2.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(purple)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
