name       : purple-facebook
version    : 0.9.3
release    : 2
source     :
    - https://github.com/dequis/purple-facebook/releases/download/v0.9.3-c9b74a765767/purple-facebook-0.9.3-c9b74a765767.tar.gz : bec38bdcc1a81172d1a1d459aa7455b146bf2dda9faa1983fcde08e674220bf3
license    : GPL-2.0
component  : network.im
summary    : Pidgin Facebook Plugin
description: |
    Purple Facebook implements the Facebook Messenger protocol into pidgin, finch, and libpurple. While the primary implementation is for purple3, this plugin is back-ported for purple2.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(purple)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
