name       : purple-facebook
version    : 20151226
release    : 1
source     :
    - https://github.com/jgeboski/purple-facebook/archive/1852eb9052a0.tar.gz : 92691e8025e07b77a1c103d09fc45eeaeafa0229d30a7b0fde6a92611326bb66
license    : GPL-2.0
component  : network.im
summary    : Pidgin Facebook Plugin
description: |
    Purple Facebook implements the Facebook Messenger protocol into pidgin, finch, and libpurple. While the primary implementation is for purple3, this plugin is back-ported for purple2.
builddeps  :
    - mercurial
    - pkgconfig(purple)
    - pkgconfig(json-glib-1.0)
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
